// <auto-generated />
namespace LinkForEmployment.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add13NewTables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add13NewTables));
        
        string IMigrationMetadata.Id
        {
            get { return "201801181408399_add13NewTables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
